# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site Settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Filipovi GitHub projekti"
description: Spletna stran s Filipovimi GitHub projekti.
# baseurl: "/"
# url: "https://projects.filips.si/"
permalink: "/:year/:month/:day/:title"
repository: "filips123/filips123.github.io"
excerpt_separator: "<!--more-->"
paginate: 5

# MatJek Specific Configurations
github_profile: "https://github.com/filips123/"
user: "Filip Š"
user_email: "projects@filips.si"
contact_url: "https://www.emailmeform.com/builder/embed/bNo6p9sMiha443fb47fG"
# google_tracking_id: "UA-96359860-1"
# google_site_verification: "UA-96359860-1"
disqus_shortname: "filips-projects"

# Other Websites
websites:
  - name: "Filipovo spletno mesto"
    url: "https://www.filips.si/"
  - name: "Filipove novice"
    url: "https://news.filips.si/"
  - name: "Spletni dnevnik o Filipovem spletnem mestu"
    url: "https://blog.filips.si/"
  - name: "Filipovi nasveti"
    url: "https://filips123.wordpress.com/"
  - name: "Filipovi programi"
    url: "https://programs.filips.si/"
  - name: "Filipovi vodiči"
    url: "https://guides.filips.si/"

# Social Links
social:
  github: filips123
  # bitbucket: 
  # hacker_news: 
  stackexchange: 8621884
  # stackoverflow: 
  twitter: filipssi
  facebook: filips.si
  # tumblr: 
  linkedin: 
  gplus: +FilipsSi
  # flickr: 

# Build Settings
timezone: Europe/Ljubljana
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
